# Generated by Django 5.1.2 on 2024-11-25 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('interest1', models.CharField(blank=True, max_length=50, null=True)),
                ('interest2', models.CharField(blank=True, max_length=50, null=True)),
                ('interest3', models.CharField(blank=True, max_length=50, null=True)),
                ('interest4', models.CharField(blank=True, max_length=50, null=True)),
                ('interest5', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
