# Generated by Django 5.1.2 on 2024-12-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0009_chatmessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
